config/routes.rb
Knightrider::Application.routes.draw do

  root 'home#index'

  devise_for :users,
    :path_names => { :sign_in => 'login', :sign_out => 'logout'},
    :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
      :sessions => "sessions"
    }

  resources :robots

end

app/models/app_config.rb
class AppConfig < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/robot.rb
class Robot < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user
  has_attached_file :avatar, styles: {
    large: ["680x400", :jpeg],
    small: ["422x300#", :jpeg]
  }, default_url: "knightrider-logo.png"

  validates_attachment :avatar,
    :presence => true,
    :content_type => { :content_type => ["image/jpg", "image/gif", "image/png", "image/jpeg"]},
    :size => { :in => 0..10.megabytes }

  validates :name, :description, :code_url, presence: true
  validates_format_of :code_url, with: URI.regexp(["http", "https"])

  friendly_id :name, use: :slugged

  def creator_name
    user.name
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:github]

  has_many :robots

  def self.find_or_create_github_auth(auth_hash)

    user = where(email: auth_hash[:info][:email]).first_or_create! do |u|
      u.password = Devise.friendly_token[0,20]
    end

    user.name = auth_hash[:info][:name]
    user.uid = auth_hash[:uid]
    user.avatar = auth_hash[:info][:image]
    user.provider = auth_hash[:provider]
    user.save if user.changed?
    user

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'application'

  #Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource)
    root_path
  end

  #Overiding devise method :authenticate_user!
  def authenticate_user!
    unless user_signed_in?
      redirect_to user_omniauth_authorize_path(:github)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @robots = Robot.all
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.friendly.find(params[:id])
  end

  def new
    @robot = Robot.new

    respond_to do |format|
      format.html #renders the new page
      format.json { render json: @robot }
    end
  end

  def create
   @robot = current_user.robots.new(robot_params)

   respond_to do |format|
     if @robot.save
       format.html { redirect_to robot_path(@robot)}
     else
       format.html { render action: "new" }
     end
   end
  end

  def edit
    @robot = Robot.find(params[:id])
  end

  def update
    @robot = Robot.find(params[:id])

    respond_to do |format|
      if @robot.update_attributes(robot_params)
        format.html { redirect_to robot_path(@robot) }
      else
        format.html { redirect_to edit_robot_path(@robot) }
      end
    end
  end


  private
  def robot_params
    params.require(:robot).permit(:name, :description, :avatar, :code_url, :video_url, :cost_to_build, :time_to_build, :programming_language)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  # # DELETE /resource/sign_out
  # def destroy
  #   redirect_path = after_sign_out_path_for(resource_name)
  #   signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))

  #   # We actually need to hardcode this as Rails default responder doesn't
  #   # support returning empty response on GET request
  #   respond_to do |format|
  #     format.all { head :no_content }
  #     format.any(*navigational_formats) { redirect_to redirect_path }
  #   end
  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github

    @user = User.find_or_create_github_auth(request.env["omniauth.auth"])
    unless @user.valid?
      set_flash_message(:notice, :success, :kind => "Github")
      return redirect_to :root
    end

    sign_in_and_redirect @user, :event => :authentication

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  ## Robot Format
  #
  # Format text to allow line breaks.
  # Provide a future method to allow for specifically
  # sanitized content
  #
  def robot_format(string)
     auto_link(simple_format(h(string)))
  end

end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/home/index.html.erb
<% content_for :js do %>
  <script>mixpanel.track('Viewed Homepage');</script>
<% end %>
<section class="hero-image-text cb">
  <div class="top-background clearfix">
    <%= image_tag asset_path("knightrider-logo.png"), class: 'knightrider-logo' %>
    <p class="headline">Instructabots</p>
    <p class="second-headline">share your robot's code, video, and story</p>
  </div>

  <div class="bottom-background"></div>
</section>

<div id="about" class="value-prop container clearfix">
  <article class="feature">
    <%= image_tag asset_path("robot-val1.png"), class: 'featured-image' %>
    <h2 class="feature-title">Code</h2>
    <p class="feature-text">Link your github repo and share your code. Lets bring social robots to social coding.</p>
  </article>
  <article class="feature">
    <%= image_tag asset_path("robot-val2.png"), class: 'featured-image' %>
    <h2 class="feature-title">Upload</h2>
    <p class="feature-text">Share your images and videos. It's time to show off what you got, for science.</p>
  </article>
  <article class="feature">
   <%= image_tag asset_path("robot-val3.png"), class: 'featured-image' %>
    <h2 class="feature-title">Share</h2>
    <p class="feature-text">Building robots is fun, but teaching someone else to build robots is even better.</p>
  </article>
</div>

<section class="section section-thoughts">
  <div class="container">
    <div class="thought">
      <h1 class="section-head-title">Say hello</h1>
      <article class="text-post">
        <p>Tell us what you need and we'll make it come true. We love and adore critical feedback. Soon we'll be open sourcing instructabots so we call all work together to make this the best place to share our Robot stories.</p>
        <p>Patches will be welcome soon. Talk to us up on twitter in the meantime.</p>
        <a href="https://twitter.com/instructabots" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @instructabots</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </article>
   </div>
  </div>
</section>

<section id="featured" class="section clearfix">
  <%= render 'shared/robots' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title><%= AppConfig.app_name %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="page-head clearfix">
  <div class="container">
    <div class="nav-logo">
      <%= link_to image_tag('knightrider-half.png'), root_path %>
    </div>
    <nav class="page-nav right">
      <ul>
        <li class="menu-item"><%= link_to "About", "/#about" %></li>
        <li class="menu-item"><%= link_to "Featured", "/#featured" %></li>
        <li class="menu-item"><%= link_to "All Robots", "/robots/" %></li>
        <% if user_signed_in? && current_user.robots.present? %>
          <li class="menu-item"><%= link_to "Your Robot",
          robot_path(current_user.robots.first) %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class="menu-item"><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <%= link_to 'Submit A Robot', new_robot_path, class: 'btn submit-robot' %>
      <% else %>
        <%= link_to 'Submit A Robot', user_omniauth_authorize_path(:github), class: 'btn submit-robot sub-btn' %>
      <% end %>

    </nav>
  </div>
</header>
<%= yield %>

<footer class="page-footer">
  <div class="copyright">
    <p class="smallprint">&copy; 2013 Copyright Instructabots <span class="space">::</span>  Made with <span class="heart">&#x2665;</span> in NYC by
    <%= link_to "Francis Gulotta", "https://twitter.com/reconbot", class: "footer-link", target: "_blank" %>
    &amp;&amp;
    <%= link_to "Rushaine McBean", "https://twitter.com/copasetickid", class: "footer-link", target: "_blank" %>
    &amp;&amp;
    <%= link_to "Zahra Jabini", "https://twitter.com/zeejab", class: "footer-link", target: "_blank" %>
    </p>
    <p><%= link_to "Patches Welcome", "https://github.com/knightrider", class: "footer-link", target: "_blank" %></p>
  </div>
  
</footer>

<%= render partial: 'shared/ga' %>
<%= render partial: 'shared/mixpanel' %>
<%= yield :js %>
</body>
</html>

app/views/robots/_form.html.erb
<section class="section">
  <div class="container">
    <div class="section-head clearfix">
      <h1 class="section-head-title">Your Robot</h1>
      <p class="section-head-content">The first step is to introduce the world to your robot.</p>
    </div>
    <div class="form-section clearfix">
      <div class="section-number">Aimless extension of knowledge, however, which is what I think you really mean by the term curiosity, is merely inefficiency. I am designed to avoid inefficiency.</div>
    <%= form_for @robot do |f| %>
      <% if @robot.errors.any? %>
        <div id="robot-errors_">
          <h2><%= pluralize(@robot.errors.count, "error") %> prohibited the creation of your robot:</h2>
          <ul>
          <% @robot.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <div class="form-row">
          <%= f.label "Robot Name*" %>
          <%= f.text_field :name, placeholder: 'Have you named your robot?', size: 40, class: 'robot-input', required: true %>
        </div>
        <div class="form-row clearfix">
          <%= f.label 'Robot Description*' %>
          <%= f.text_area :description, placeholder: 'Tell us about your robot here...', class: 'robot-input robot-description' , required: true %>
        </div>

        <div class="form-row clearfix">
          <%= f.label 'Robot Avatar*' %>
          <%= f.file_field :avatar, class: 'robot-image' , required: true %>
        </div>

        <div class="form-row clearfix">
          <%= f.label 'Source Code*' %>
          <%= f.text_field :code_url, placeholder: 'Link to your source code ', size: 40, class: 'robot-input' , required: true %>
        </div>

        <div class="form-row clearfix">
          <%= f.label 'Youtube Video*' %>
          <%= f.text_field :video_url, placeholder: 'Link to your video', size: 40, class: 'robot-input' %>
        </div>

        <div class="form-row clearfix">
          <%= f.label 'Cost' %>
          <%= f.text_field :cost_to_build , placeholder: 'Enter amount', class: 'robot-input' %>
        </div>

        <div class="form-row clearfix">
          <%= f.label 'Hours to Build' %>
          <%= f.text_field :time_to_build, placeholder: 'How long did it take you to build it?', class: 'robot-input' %>
        </div>

         <div class="form-row clearfix">
          <%= f.label 'Programming Language' %>
          <%= f.text_field :programming_language, placeholder: 'What was it built in?', size: 40, class: 'robot-input' %>
        </div>

        <%= f.button :submit, class: 'btn btn-submit' %>
      <% end %>
    </div>
  </div>
</section>

app/views/robots/_robot.html.erb
<article class="robot-box">
  <%= image_tag robot.avatar(:small) %>
  <div class="robots-overlay-effect">
    <%= link_to robot do %>
      <div class="effect-contents-inner">
        <h2><%= robot.name %></h2>
      </div>
    <% end %>
  </div>
</article>

app/views/robots/edit.html.erb
Edit Your Robot

<%= render 'form' %>

app/views/robots/index.html.erb
<section class="section">
  	<div class="container">
	   <header class="section-head">
	    	<h1 class="section-head-title">
	    	All the Robots
	    	</h1>
	  	</header>
 	</div>
</section>

<section class="section clearfix"
	<div class="container ">
	  <%= render  @robots %>
	</div>
</section>

app/views/robots/new.html.erb
<% content_for :js do %>
  <script>mixpanel.track('Viewed New Bot Form');</script>
<% end %>

<section class="hero-mega-text cb">
  <div class="container">
    <h1 class="hero-mega-title">I am not a robot. I have a heart, and I bleed.</h1>
  </div>
</section>
<%= render 'form' %>

app/views/robots/show.html.erb
<section class="section robots-case-study">
  <div class="case-study-author">
    <div class="case-study-container">
      <h1 class="case-study-title"><%= @robot.name %> </h1>
        <p><strong>by <%= @robot.creator_name %> </strong></p>
    </div>
  </div>

  <div class="case-study-about-robot clearfix">
    <div class="arrows">
      <%= image_tag 'arrow-yellow.png', style: 'width: 35px; height: 12px;', class: 'up' %>
      <%= image_tag 'arrow-blue.png', style: 'width: 35px; height: 12px;', class: 'down' %>
    </div>
    <div class="case-study-robot-image" style="overflow: hidden; position: relative;">
      <%= image_tag @robot.avatar.url(:large) %>
    </div>
    <div class="robot-about">
      <div class="text">
        <p class="feature-text"><%= robot_format(@robot.description) %> </p>
        <% if @robot.code_url.present? %>
          <%= link_to 'Code', @robot.code_url, class: "btn btn-white", target: "_blank" %>
        <% end %>
        <% if @robot.video_url.present? %>
          <div class="video">
            <%= YouTubeAddy.youtube_embed_url(@robot.video_url,420,315).html_safe %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="grid clearfix">
    </div>
  </div>
</section>

app/views/shared/_ga.html.erb
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44261259-2', 'instructabots.com');
  ga('send', 'pageview');

</script>
<% end %>

app/views/shared/_mixpanel.html.erb
<script type="text/javascript">
<% if Rails.env.production? %>
(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
mixpanel.init("7109168de02fd690072d988d31d0a50a");
<% else %>
window.mixpanel = {
  track: function(){}
};
<% end %>
</script>

app/views/shared/_robots.html.erb
<div class="container">
  <header class="section-head">
    <h1 class="section-head-title">Featured Robots</h1>
  </header>
</div>

<div class="container">
  <%= render @robots %>
</div>